import { Template, Order, DashboardStats } from '@/types';

export const mockTemplates: Template[] = [
  {
    id: '1',
    name: 'E-Commerce Modern',
    description: 'Template toko online modern dengan fitur lengkap, responsive design, dan user experience yang optimal.',
    category: 'E-Commerce',
    price: 299000,
    image: 'https://via.placeholder.com/400x300/3B82F6/FFFFFF?text=E-Commerce+Modern',
    previewUrl: 'https://demo.langsadev.com/ecommerce-modern',
    features: ['Responsive Design', 'Shopping Cart', 'Payment Gateway', 'Admin Panel', 'SEO Optimized'],
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'TypeScript'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    name: 'Corporate Business',
    description: 'Template website perusahaan profesional dengan landing page yang menarik dan fitur company profile.',
    category: 'Corporate',
    price: 199000,
    image: 'https://via.placeholder.com/400x300/10B981/FFFFFF?text=Corporate+Business',
    previewUrl: 'https://demo.langsadev.com/corporate-business',
    features: ['Landing Page', 'About Us', 'Services', 'Contact Form', 'Blog'],
    technologies: ['React', 'Next.js', 'Tailwind CSS'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '3',
    name: 'Restaurant & Cafe',
    description: 'Template untuk restoran dan cafe dengan menu online, reservasi, dan galeri foto makanan.',
    category: 'Restaurant',
    price: 249000,
    image: 'https://via.placeholder.com/400x300/F59E0B/FFFFFF?text=Restaurant+Cafe',
    previewUrl: 'https://demo.langsadev.com/restaurant-cafe',
    features: ['Online Menu', 'Reservation System', 'Gallery', 'Location Map', 'Reviews'],
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'Framer Motion'],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: '4',
    name: 'Portfolio Creative',
    description: 'Template portfolio kreatif untuk designer, fotografer, dan creative professional.',
    category: 'Portfolio',
    price: 149000,
    image: 'https://via.placeholder.com/400x300/8B5CF6/FFFFFF?text=Portfolio+Creative',
    previewUrl: 'https://demo.langsadev.com/portfolio-creative',
    features: ['Portfolio Gallery', 'About Section', 'Contact Form', 'Blog', 'Dark Mode'],
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'Framer Motion'],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: '5',
    name: 'Medical Clinic',
    description: 'Template untuk klinik dan rumah sakit dengan sistem appointment dan informasi dokter.',
    category: 'Medical',
    price: 349000,
    image: 'https://via.placeholder.com/400x300/EF4444/FFFFFF?text=Medical+Clinic',
    previewUrl: 'https://demo.langsadev.com/medical-clinic',
    features: ['Doctor Profiles', 'Appointment Booking', 'Services', 'Medical News', 'Contact'],
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'TypeScript'],
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: '6',
    name: 'Educational Platform',
    description: 'Template untuk platform pembelajaran online dengan sistem kursus dan progress tracking.',
    category: 'Education',
    price: 399000,
    image: 'https://via.placeholder.com/400x300/06B6D4/FFFFFF?text=Educational+Platform',
    previewUrl: 'https://demo.langsadev.com/educational-platform',
    features: ['Course Management', 'Student Dashboard', 'Video Player', 'Quiz System', 'Certificates'],
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'TypeScript', 'Video.js'],
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-22'),
  },
];

export const mockOrders: Order[] = [
  {
    id: '1',
    customerName: 'Budi Santoso',
    customerEmail: 'budi@email.com',
    customerPhone: '081234567890',
    templateId: '1',
    template: mockTemplates[0],
    message: 'Saya tertarik dengan template E-Commerce Modern. Apakah bisa diCustomize sesuai kebutuhan bisnis saya?',
    status: 'pending',
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '2',
    customerName: 'Sari Dewi',
    customerEmail: 'sari@email.com',
    customerPhone: '087654321098',
    templateId: '2',
    template: mockTemplates[1],
    message: 'Halo, saya ingin memesan template Corporate Business untuk website perusahaan kami.',
    status: 'in-progress',
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '3',
    customerName: 'Ahmad Rahman',
    customerEmail: 'ahmad@email.com',
    customerPhone: '089876543210',
    templateId: '3',
    template: mockTemplates[2],
    message: 'Template Restaurant & Cafe sangat menarik. Berapa lama waktu implementasinya?',
    status: 'completed',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-21'),
  },
];

export const mockStats: DashboardStats = {
  totalTemplates: mockTemplates.length,
  totalOrders: mockOrders.length,
  pendingOrders: mockOrders.filter(order => order.status === 'pending').length,
  monthlyRevenue: 2450000,
};